{% set name = "randonneur" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b0f8632e04906196ca5986b2491b09e2d6ea2fd07724baf624c729687552a9c0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-build-isolation --no-deps . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=68.0
  run:
    - loguru
    - openpyxl <=3.2
    - pydantic
    - python >={{ python_min }}
    - randonneur_data
    - stats_arrays
    - tqdm
    - xlsxwriter

test:
  imports:
    - randonneur
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://randonneur.readthedocs.io/
  summary: 'Library to apply flexible changes to datasets'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://randonneur.readthedocs.io/
  dev_url: https://github.com/brightway-lca/randonneur

extra:
  recipe-maintainers:
    - m-rossi
